on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4 # This action

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build default package
        run: nix build
